In [ ]:
import os
import time
import random
import math
import re
import pandas as pd
from urllib.parse import urlparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from collections import Counter
import whois
import tldextract
import numpy as np

In [ ]:
extractor = tldextract.TLDExtract(cache_dir='.tld_cache', suffix_list_urls=None)
ip_pattern = re.compile(r'^\d{1,3}(\.\d{1,3}){3}$')
shorteners_set = {"bit.ly", "t.co", "tinyurl.com", "goo.gl", "ow.ly", "is.gd", "buff.ly", "cutt.ly"}
keywords_set = {"secure", "account", "update", "free", "lucky", "bonus", "click", "offer", "winner", "login", "verify", "banking", "confirm", "password", "signin"}

In [ ]:
def url_entropy(s: str) -> float:
    if not s:
        return 0.0
    probs = [c / len(s) for c in Counter(s).values()]
    return -sum(p * math.log2(p) for p in probs)

In [ ]:
def normalize_date(value):
    if value is None:
        return None
    if isinstance(value, pd.Timestamp):
        return value.to_pydatetime()
    if isinstance(value, list):
        flat = []
        for v in value:
            if isinstance(v, list):
                flat.extend(v)
            else:
                flat.append(v)
        flat = [v for v in flat if v is not None]
        if not flat:
            return None
        return flat[0]
    return value

In [ ]:
"""
def extract_whois_features(features, url):
    try:
        w = whois.whois(url)
        creation = normalize_date(w.creation_date)
        expiration = normalize_date(w.expiration_date)

        now = pd.Timestamp.now()
        features["domain_age"] = (now - pd.Timestamp(creation)).days if creation else -1
        features["days_to_expire"] = (pd.Timestamp(expiration) - now).days if expiration else -1
        features["registration_length"] = (
            (pd.Timestamp(expiration) - pd.Timestamp(creation)).days
            if creation and expiration else -1
        )

    except Exception as e:
        print(f"⚠️ WHOIS chyba pri {url}: {e}")
        features["domain_age"] = -1
        features["days_to_expire"] = -1
        features["registration_length"] = -1

    return features
"""

In [ ]:
def extract_whois_features(features, url):
    try:
        w = whois.whois(url)
        creation = normalize_date(w.creation_date)
        expiration = normalize_date(w.expiration_date)

        now = pd.Timestamp.now(tz="UTC").tz_localize(None)

        if creation is not None:
            c = pd.Timestamp(creation).tz_localize(None)
            domain_age = (now - c).days
        else:
            domain_age = -1

        if expiration is not None:
            e = pd.Timestamp(expiration).tz_localize(None)
            days_to_expire = (e - now).days
        else:
            days_to_expire = -1

        if creation is not None and expiration is not None:
            registration_length = (e - c).days
        else:
            registration_length = -1

        features["domain_age"] = domain_age
        features["days_to_expire"] = days_to_expire
        features["registration_length"] = registration_length

    except Exception as e:
        print(f"⚠️ WHOIS chyba pri {url}: {e}")
        features["domain_age"] = -1
        features["days_to_expire"] = -1
        features["registration_length"] = -1

    return features

In [ ]:
def extract_url_features(url: str, phishing: int = 0) -> dict:
    parsed = urlparse(url)
    hostname = parsed.hostname or ""
    path = parsed.path or ""
    query = parsed.query or ""

    ext = extractor(url)
    url_lower = url.lower()

    full_domain = f"{ext.domain}"
    if ext.suffix and not full_domain.endswith(ext.suffix):
        full_domain += f".{ext.suffix}"

    features = {
        "phishing": phishing,
        "url": url,
        "url_len": len(url),
        "host_len": len(hostname),
        "path_len": len(path),
        "query_len": len(query),
        "is_https": 1 if parsed.scheme == "https" else 0,
        "count_dots": hostname.count("."),
        "count_hyphen": url.count("-"),
        "count_at": url.count("@"),
        "count_qm": url.count("?"),
        "count_eq": url.count("="),
        "count_slash": url.count("/"),
        "count_double_slash": url.count("//") - 1 if url.count("//") > 1 else 0,
        "count_digits": sum(c.isdigit() for c in url),
        "has_ip": 1 if ip_pattern.match(hostname) else 0,
        "has_shortener": 1 if full_domain in shorteners_set else 0,
        "has_keyword": 1 if any(kw in url_lower for kw in keywords_set) else 0,
        "subdomain_len": len(ext.subdomain),
        "domain": ext.domain,
        "suffix": ext.suffix,
        "domain_entropy": url_entropy(hostname)
    }

    extract_whois_features(features, full_domain)
    
    return features

In [ ]:
def worker(url: str, phishing: int, retries: int = 9, delay: float = 0.5):
    for attempt in range(1, retries + 1):
        try:
            features = extract_url_features(url, phishing)

            # Retry ak WHOIS neúspešný
            if features.get("domain_age", -1) == -1 and attempt < retries:
                raise ValueError("WHOIS failed, retrying...")

            if attempt > 1:
                print(f"✅ {url} succeeded on attempt {attempt}")
            return features

        except Exception as e:
            print(f"⚠️ {url} attempt {attempt}/{retries} failed: {e}")
            if attempt < retries:
                time.sleep(delay * attempt + random.uniform(0, 0.3))
            else:
                print(f"❌ {url} failed all {retries} attempts")
    return None

In [ ]:
def process_urls(input_file: str, output_file: str, phishing: int = 0, max_workers: int = 10, limit: int = None):
    """Spracuje URL zo súboru (txt alebo csv) paralelne s retry logikou."""
    # Načítanie URL
    if input_file.endswith(".csv"):
        df = pd.read_csv(input_file)
        urls = df["url"].astype(str).tolist() if "url" in df.columns else df.iloc[:, 0].astype(str).tolist()
    else:
        with open(input_file, "r", encoding="utf-8", errors="ignore") as f:
            urls = [line.strip() for line in f if line.strip()]

    if limit:
        urls = urls[:limit]

    records = []
    failed = []

    print(f"🧩 Načítaných {len(urls)} URL, spúšťam spracovanie s {max_workers} vláknami...")

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(worker, u, phishing): u for u in urls}
        total = len(futures)

        for i, future in enumerate(as_completed(futures), 1):
            u = futures[future]
            try:
                res = future.result()
                if res:
                    records.append(res)
                else:
                    records.append(u)
            except Exception as e:
                print(f"❌ Výnimka pri {u}: {e}")
                records.append(u)

            if i % 20 == 0 or i == total:
                print(f"Progress {i}/{total} | Success: {len(records)} | Failed: {len(failed)}")
                if records:
                    out_df = pd.DataFrame(records)
                    out_df.to_csv(output_file, index=False, mode='a', header=not os.path.exists(output_file))
                    records.clear()

    print(f"✅ Hotovo. Výsledok: {output_file}")
    return pd.read_csv(output_file) if os.path.exists(output_file) else pd.DataFrame()

In [ ]:
df = process_urls(
    input_file="../dataset/phishing1.txt",
    output_file="../dataset/df_phishing1.csv",
    phishing=1,
    max_workers=70,
    limit=20000
)

In [ ]:
df = process_urls(
    input_file="../dataset/without_www.txt",
    output_file="../dataset/df_benign1.csv",
    phishing=0,
    max_workers=50,
    limit=8000
)

In [ ]:
import pandas as pd
import re
import tldextract
import math
from collections import Counter
import urllib.parse

def shannon_entropy(s):
    if not s:
        return 0
    freq = Counter(s)
    probs = [f / len(s) for f in freq.values()]
    return -sum(p * math.log2(p) for p in probs)

def extract_new_features(url):
    try:
        parsed = urllib.parse.urlparse(url)
        ext = tldextract.extract(url)
        domain = ext.domain or ""
        subdomain = ext.subdomain or ""
        path = parsed.path or ""
        
        feats = {}

        # 🔹 Struktúrne
        feats["num_subdomains"] = subdomain.count(".") + (1 if subdomain else 0)
        feats["path_depth"] = path.count("/")
        feats["has_www"] = 1 if "www" in subdomain else 0
        feats["has_double_https"] = 1 if url.count("https") > 1 else 0
        feats["has_port"] = 1 if ":" in parsed.netloc else 0
        feats["has_fragment"] = 1 if parsed.fragment else 0
        feats["url_ratio_digits"] = sum(c.isdigit() for c in url) / len(url)
        specials = re.findall(r"[-@=?%_/\.]", url)
        feats["url_ratio_specials"] = len(specials) / len(url)
        feats["contains_encoded_chars"] = 1 if "%" in url else 0
        feats["has_repeat_chars"] = 1 if re.search(r"(.)\1{3,}", url) else 0

        # 🔹 Doména
        feats["domain_entropy"] = shannon_entropy(domain)
        feats["domain_char_diversity"] = len(set(domain)) / len(domain) if domain else 0
        feats["domain_has_digit"] = 1 if any(c.isdigit() for c in domain) else 0
        feats["domain_starts_with_digit"] = 1 if domain and domain[0].isdigit() else 0
        feats["tld_length"] = len(ext.suffix or "")
        feats["entropy_per_len"] = feats["domain_entropy"] / (len(domain)+1)

        return feats
    except Exception as e:
        print(f"Chyba pri URL {url}: {e}")
        return None

def process_urls_txt(input_txt, output_csv="url_new_features.csv"):
    # Načítaj txt, každý riadok je URL
    with open(input_txt, "r", encoding="utf-8") as f:
        urls = [line.strip() for line in f if line.strip()]

    all_feats = []
    for i, url in enumerate(urls, 1):
        feats = extract_new_features(url)
        if feats:
            feats["url"] = url
            all_feats.append(feats)
        if i % 100 == 0:
            print(f"✅ Spracovaných {i} URL...")

    df_features = pd.DataFrame(all_feats)
    df_features.to_csv(output_csv, index=False)
    print(f"\n✅ Uložené do súboru: {output_csv}")
    print(f"Počet spracovaných URL: {len(df_features)}")
    return df_features

# 🔹 Použitie:
# df_new = process_urls_txt("urls.txt", "url_new_features.csv")

In [2]:
process_urls_txt("../dataset/phishing1.txt", "../dataset/url_new_features_phishing1.csv")

✅ Spracovaných 100 URL...
✅ Spracovaných 200 URL...
✅ Spracovaných 300 URL...
✅ Spracovaných 400 URL...
✅ Spracovaných 500 URL...
✅ Spracovaných 600 URL...
✅ Spracovaných 700 URL...
✅ Spracovaných 800 URL...
✅ Spracovaných 900 URL...
✅ Spracovaných 1000 URL...
✅ Spracovaných 1100 URL...
✅ Spracovaných 1200 URL...
✅ Spracovaných 1300 URL...
✅ Spracovaných 1400 URL...
✅ Spracovaných 1500 URL...
✅ Spracovaných 1600 URL...
✅ Spracovaných 1700 URL...
✅ Spracovaných 1800 URL...
✅ Spracovaných 1900 URL...
✅ Spracovaných 2000 URL...
✅ Spracovaných 2100 URL...
✅ Spracovaných 2200 URL...
✅ Spracovaných 2300 URL...
✅ Spracovaných 2400 URL...
✅ Spracovaných 2500 URL...
✅ Spracovaných 2600 URL...
✅ Spracovaných 2700 URL...
✅ Spracovaných 2800 URL...
✅ Spracovaných 2900 URL...
✅ Spracovaných 3000 URL...
✅ Spracovaných 3100 URL...
✅ Spracovaných 3200 URL...
✅ Spracovaných 3300 URL...
✅ Spracovaných 3400 URL...
✅ Spracovaných 3500 URL...
✅ Spracovaných 3600 URL...
✅ Spracovaných 3700 URL...
✅ Spracovaných 3800 URL...
✅ Spracovaných 3900 URL...
✅ Spracovaných 4000 URL...
✅ Spracovaných 4100 URL...
✅ Spracovaných 4200 URL...
✅ Spracovaných 4300 URL...
✅ Spracovaných 4400 URL...
✅ Spracovaných 4500 URL...
✅ Spracovaných 4600 URL...
✅ Spracovaných 4700 URL...
✅ Spracovaných 4800 URL...
✅ Spracovaných 4900 URL...
✅ Spracovaných 5000 URL...
✅ Spracovaných 5100 URL...
✅ Spracovaných 5200 URL...
✅ Spracovaných 5300 URL...
✅ Spracovaných 5400 URL...
✅ Spracovaných 5500 URL...
✅ Spracovaných 5600 URL...
✅ Spracovaných 5700 URL...
✅ Spracovaných 5800 URL...
✅ Spracovaných 5900 URL...
✅ Spracovaných 6000 URL...
✅ Spracovaných 6100 URL...
✅ Spracovaných 6200 URL...
✅ Spracovaných 6300 URL...
✅ Spracovaných 6400 URL...
✅ Spracovaných 6500 URL...
✅ Spracovaných 6600 URL...
✅ Spracovaných 6700 URL...
✅ Spracovaných 6800 URL...
✅ Spracovaných 6900 URL...
✅ Spracovaných 7000 URL...
✅ Spracovaných 7100 URL...
✅ Spracovaných 7200 URL...
✅ Spracovaných 7300 URL...
✅ Spracovaných 7400 URL...
✅ Spracovaných 7500 URL...
✅ Spracovaných 7600 URL...
✅ Spracovaných 7700 URL...
✅ Spracovaných 7800 URL...
✅ Spracovaných 7900 URL...
✅ Spracovaných 8000 URL...
✅ Spracovaných 8100 URL...
✅ Spracovaných 8200 URL...
✅ Spracovaných 8300 URL...
✅ Spracovaných 8400 URL...
✅ Spracovaných 8500 URL...
✅ Spracovaných 8600 URL...
✅ Spracovaných 8700 URL...
✅ Spracovaných 8800 URL...
✅ Spracovaných 8900 URL...
✅ Spracovaných 9000 URL...
✅ Spracovaných 9100 URL...
✅ Spracovaných 9200 URL...
✅ Spracovaných 9300 URL...
✅ Spracovaných 9400 URL...
✅ Spracovaných 9500 URL...
✅ Spracovaných 9600 URL...
✅ Spracovaných 9700 URL...
✅ Spracovaných 9800 URL...
✅ Spracovaných 9900 URL...
✅ Spracovaných 10000 URL...
✅ Spracovaných 10100 URL...
✅ Spracovaných 10200 URL...
✅ Spracovaných 10300 URL...
✅ Spracovaných 10400 URL...
✅ Spracovaných 10500 URL...
✅ Spracovaných 10600 URL...
✅ Spracovaných 10700 URL...
✅ Spracovaných 10800 URL...
✅ Spracovaných 10900 URL...
✅ Spracovaných 11000 URL...
✅ Spracovaných 11100 URL...
✅ Spracovaných 11200 URL...
✅ Spracovaných 11300 URL...
✅ Spracovaných 11400 URL...
✅ Spracovaných 11500 URL...
✅ Spracovaných 11600 URL...
✅ Spracovaných 11700 URL...
✅ Spracovaných 11800 URL...
✅ Spracovaných 11900 URL...
✅ Spracovaných 12000 URL...
✅ Spracovaných 12100 URL...
✅ Spracovaných 12200 URL...
✅ Spracovaných 12300 URL...
✅ Spracovaných 12400 URL...
✅ Spracovaných 12500 URL...
✅ Spracovaných 12600 URL...
✅ Spracovaných 12700 URL...
✅ Spracovaných 12800 URL...
✅ Spracovaných 12900 URL...
✅ Spracovaných 13000 URL...
✅ Spracovaných 13100 URL...
✅ Spracovaných 13200 URL...
✅ Spracovaných 13300 URL...
✅ Spracovaných 13400 URL...
✅ Spracovaných 13500 URL...
✅ Spracovaných 13600 URL...
✅ Spracovaných 13700 URL...
✅ Spracovaných 13800 URL...
✅ Spracovaných 13900 URL...
✅ Spracovaných 14000 URL...
✅ Spracovaných 14100 URL...
✅ Spracovaných 14200 URL...
✅ Spracovaných 14300 URL...
✅ Spracovaných 14400 URL...
✅ Spracovaných 14500 URL...
✅ Spracovaných 14600 URL...
✅ Spracovaných 14700 URL...
✅ Spracovaných 14800 URL...
✅ Spracovaných 14900 URL...
✅ Spracovaných 15000 URL...
✅ Spracovaných 15100 URL...
✅ Spracovaných 15200 URL...
✅ Spracovaných 15300 URL...
✅ Spracovaných 15400 URL...
✅ Spracovaných 15500 URL...
✅ Spracovaných 15600 URL...
✅ Spracovaných 15700 URL...
✅ Spracovaných 15800 URL...
✅ Spracovaných 15900 URL...
✅ Spracovaných 16000 URL...
✅ Spracovaných 16100 URL...
✅ Spracovaných 16200 URL...
✅ Spracovaných 16300 URL...
✅ Spracovaných 16400 URL...
✅ Spracovaných 16500 URL...
✅ Spracovaných 16600 URL...
✅ Spracovaných 16700 URL...
✅ Spracovaných 16800 URL...
✅ Spracovaných 16900 URL...
✅ Spracovaných 17000 URL...
✅ Spracovaných 17100 URL...
✅ Spracovaných 17200 URL...
✅ Spracovaných 17300 URL...
✅ Spracovaných 17400 URL...
✅ Spracovaných 17500 URL...
✅ Spracovaných 17600 URL...
✅ Spracovaných 17700 URL...
✅ Spracovaných 17800 URL...
✅ Spracovaných 17900 URL...
✅ Spracovaných 18000 URL...
✅ Spracovaných 18100 URL...
✅ Spracovaných 18200 URL...
✅ Spracovaných 18300 URL...
✅ Spracovaných 18400 URL...
✅ Spracovaných 18500 URL...
✅ Spracovaných 18600 URL...
✅ Spracovaných 18700 URL...
✅ Spracovaných 18800 URL...
✅ Spracovaných 18900 URL...
✅ Spracovaných 19000 URL...
✅ Spracovaných 19100 URL...
✅ Spracovaných 19200 URL...
✅ Spracovaných 19300 URL...
✅ Spracovaných 19400 URL...
✅ Spracovaných 19500 URL...
✅ Spracovaných 19600 URL...
✅ Spracovaných 19700 URL...
✅ Spracovaných 19800 URL...
✅ Spracovaných 19900 URL...
✅ Spracovaných 20000 URL...

✅ Uložené do súboru: ../dataset/url_new_features_phishing1.csv
Počet spracovaných URL: 20000

,num_subdomains,path_depth,has_www,has_double_https,has_port,has_fragment,url_ratio_digits,url_ratio_specials,contains_encoded_chars,has_repeat_chars,domain_entropy,domain_char_diversity,domain_has_digit,domain_starts_with_digit,tld_length,entropy_per_len,url
0,3,2,0,0,0,0,0.123596,0.101124,0,0,2.521641,0.857143,0,0,3,0.315205,https://igg54qtsmn5l0du.blob.core.windows.net/...
1,1,1,0,0,0,0,0.088889,0.111111,0,0,3.084963,0.750000,0,0,4,0.237305,https://pay.cliquecursos.site/YL9jZDWD7oO3p4q
2,1,2,0,0,0,0,0.125000,0.135417,0,0,3.640224,0.866667,1,0,3,0.227514,https://allegro-lokalnie.pl-oferta527121.icu/o...
3,5,2,0,0,0,0,0.258065,0.177419,0,0,2.355389,0.500000,0,0,3,0.181184,https://37.35.109.208.host.secureserver.net/us...
4,1,1,0,0,0,0,0.098592,0.140845,0,0,3.277613,0.909091,0,0,3,0.273134,https://zyjhgdtzunkx.myfunnelish.com/new-thank...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,1,1,0,0,0,0,0.000000,0.166667,0,0,3.027169,0.818182,0,0,3,0.252264,https://rfp-sharing.myportfolio.com/
19996,1,2,0,0,0,0,0.052632,0.157895,0,0,3.000000,1.000000,0,0,3,0.333333,https://rp.mockplus.com/rps/XujY3xX0bg
19997,1,3,0,0,0,0,0.136842,0.084211,0,0,3.238901,0.769231,0,0,2,0.231350,https://ipfs.best-practice.se/ipfs/bafybeiaw25...
19998,1,1,0,0,0,0,0.000000,0.150000,0,0,2.521641,0.857143,0,0,3,0.315205,https://terfanfranck.wixsite.com/my-site
19999,1,0,0,0,0,0,0.000000,0.102564,0,0,3.277613,0.909091,0,0,3,0.273134,https://prubancoinforma.webcindario.com

In [3]:
process_urls_txt("../dataset/benign1.txt", "../dataset/url_new_features_benign1.csv")

✅ Spracovaných 100 URL...
✅ Spracovaných 200 URL...
✅ Spracovaných 300 URL...
✅ Spracovaných 400 URL...
✅ Spracovaných 500 URL...
✅ Spracovaných 600 URL...
✅ Spracovaných 700 URL...
✅ Spracovaných 800 URL...
✅ Spracovaných 900 URL...
✅ Spracovaných 1000 URL...
✅ Spracovaných 1100 URL...
✅ Spracovaných 1200 URL...
✅ Spracovaných 1300 URL...
✅ Spracovaných 1400 URL...
✅ Spracovaných 1500 URL...
✅ Spracovaných 1600 URL...
✅ Spracovaných 1700 URL...
✅ Spracovaných 1800 URL...
✅ Spracovaných 1900 URL...
✅ Spracovaných 2000 URL...
✅ Spracovaných 2100 URL...
✅ Spracovaných 2200 URL...
✅ Spracovaných 2300 URL...
✅ Spracovaných 2400 URL...
✅ Spracovaných 2500 URL...
✅ Spracovaných 2600 URL...
✅ Spracovaných 2700 URL...
✅ Spracovaných 2800 URL...
✅ Spracovaných 2900 URL...
✅ Spracovaných 3000 URL...
✅ Spracovaných 3100 URL...
✅ Spracovaných 3200 URL...
✅ Spracovaných 3300 URL...
✅ Spracovaných 3400 URL...
✅ Spracovaných 3500 URL...
✅ Spracovaných 3600 URL...
✅ Spracovaných 3700 URL...
✅ Spracovaných 3800 URL...
✅ Spracovaných 3900 URL...
✅ Spracovaných 4000 URL...
✅ Spracovaných 4100 URL...
✅ Spracovaných 4200 URL...
✅ Spracovaných 4300 URL...
✅ Spracovaných 4400 URL...
✅ Spracovaných 4500 URL...
✅ Spracovaných 4600 URL...
✅ Spracovaných 4700 URL...
✅ Spracovaných 4800 URL...
✅ Spracovaných 4900 URL...
✅ Spracovaných 5000 URL...
✅ Spracovaných 5100 URL...
✅ Spracovaných 5200 URL...
✅ Spracovaných 5300 URL...
✅ Spracovaných 5400 URL...
✅ Spracovaných 5500 URL...
✅ Spracovaných 5600 URL...
✅ Spracovaných 5700 URL...
✅ Spracovaných 5800 URL...
✅ Spracovaných 5900 URL...
✅ Spracovaných 6000 URL...
✅ Spracovaných 6100 URL...
✅ Spracovaných 6200 URL...
✅ Spracovaných 6300 URL...
✅ Spracovaných 6400 URL...
✅ Spracovaných 6500 URL...
✅ Spracovaných 6600 URL...
✅ Spracovaných 6700 URL...
✅ Spracovaných 6800 URL...
✅ Spracovaných 6900 URL...
✅ Spracovaných 7000 URL...
✅ Spracovaných 7100 URL...
✅ Spracovaných 7200 URL...
✅ Spracovaných 7300 URL...
✅ Spracovaných 7400 URL...
✅ Spracovaných 7500 URL...
✅ Spracovaných 7600 URL...
✅ Spracovaných 7700 URL...
✅ Spracovaných 7800 URL...
✅ Spracovaných 7900 URL...
✅ Spracovaných 8000 URL...
✅ Spracovaných 8100 URL...
✅ Spracovaných 8200 URL...
✅ Spracovaných 8300 URL...
✅ Spracovaných 8400 URL...
✅ Spracovaných 8500 URL...
✅ Spracovaných 8600 URL...
✅ Spracovaných 8700 URL...
✅ Spracovaných 8800 URL...
✅ Spracovaných 8900 URL...
✅ Spracovaných 9000 URL...
✅ Spracovaných 9100 URL...
✅ Spracovaných 9200 URL...
✅ Spracovaných 9300 URL...
✅ Spracovaných 9400 URL...
✅ Spracovaných 9500 URL...
✅ Spracovaných 9600 URL...
✅ Spracovaných 9700 URL...
✅ Spracovaných 9800 URL...
✅ Spracovaných 9900 URL...
✅ Spracovaných 10000 URL...
✅ Spracovaných 10100 URL...
✅ Spracovaných 10200 URL...
✅ Spracovaných 10300 URL...
✅ Spracovaných 10400 URL...
✅ Spracovaných 10500 URL...
✅ Spracovaných 10600 URL...
✅ Spracovaných 10700 URL...
✅ Spracovaných 10800 URL...
✅ Spracovaných 10900 URL...
✅ Spracovaných 11000 URL...
✅ Spracovaných 11100 URL...
✅ Spracovaných 11200 URL...
✅ Spracovaných 11300 URL...
✅ Spracovaných 11400 URL...
✅ Spracovaných 11500 URL...
✅ Spracovaných 11600 URL...
✅ Spracovaných 11700 URL...
✅ Spracovaných 11800 URL...
✅ Spracovaných 11900 URL...
✅ Spracovaných 12000 URL...
✅ Spracovaných 12100 URL...
✅ Spracovaných 12200 URL...
✅ Spracovaných 12300 URL...
✅ Spracovaných 12400 URL...
✅ Spracovaných 12500 URL...
✅ Spracovaných 12600 URL...
✅ Spracovaných 12700 URL...
✅ Spracovaných 12800 URL...
✅ Spracovaných 12900 URL...
✅ Spracovaných 13000 URL...
✅ Spracovaných 13100 URL...
✅ Spracovaných 13200 URL...
✅ Spracovaných 13300 URL...
✅ Spracovaných 13400 URL...
✅ Spracovaných 13500 URL...
✅ Spracovaných 13600 URL...
✅ Spracovaných 13700 URL...
✅ Spracovaných 13800 URL...
✅ Spracovaných 13900 URL...
✅ Spracovaných 14000 URL...
✅ Spracovaných 14100 URL...
✅ Spracovaných 14200 URL...
✅ Spracovaných 14300 URL...
✅ Spracovaných 14400 URL...
✅ Spracovaných 14500 URL...
✅ Spracovaných 14600 URL...
✅ Spracovaných 14700 URL...
✅ Spracovaných 14800 URL...
✅ Spracovaných 14900 URL...
✅ Spracovaných 15000 URL...
✅ Spracovaných 15100 URL...
✅ Spracovaných 15200 URL...
✅ Spracovaných 15300 URL...
✅ Spracovaných 15400 URL...
✅ Spracovaných 15500 URL...
✅ Spracovaných 15600 URL...
✅ Spracovaných 15700 URL...
✅ Spracovaných 15800 URL...
✅ Spracovaných 15900 URL...
✅ Spracovaných 16000 URL...
✅ Spracovaných 16100 URL...
✅ Spracovaných 16200 URL...
✅ Spracovaných 16300 URL...
✅ Spracovaných 16400 URL...
✅ Spracovaných 16500 URL...
✅ Spracovaných 16600 URL...
✅ Spracovaných 16700 URL...
✅ Spracovaných 16800 URL...
✅ Spracovaných 16900 URL...
✅ Spracovaných 17000 URL...
✅ Spracovaných 17100 URL...
✅ Spracovaných 17200 URL...
✅ Spracovaných 17300 URL...
✅ Spracovaných 17400 URL...
✅ Spracovaných 17500 URL...
✅ Spracovaných 17600 URL...
✅ Spracovaných 17700 URL...
✅ Spracovaných 17800 URL...
✅ Spracovaných 17900 URL...
✅ Spracovaných 18000 URL...
✅ Spracovaných 18100 URL...
✅ Spracovaných 18200 URL...
✅ Spracovaných 18300 URL...
✅ Spracovaných 18400 URL...
✅ Spracovaných 18500 URL...
✅ Spracovaných 18600 URL...
✅ Spracovaných 18700 URL...
✅ Spracovaných 18800 URL...
✅ Spracovaných 18900 URL...
✅ Spracovaných 19000 URL...
✅ Spracovaných 19100 URL...
✅ Spracovaných 19200 URL...
✅ Spracovaných 19300 URL...
✅ Spracovaných 19400 URL...
✅ Spracovaných 19500 URL...
✅ Spracovaných 19600 URL...
✅ Spracovaných 19700 URL...
✅ Spracovaných 19800 URL...
✅ Spracovaných 19900 URL...
✅ Spracovaných 20000 URL...
✅ Spracovaných 20100 URL...
✅ Spracovaných 20200 URL...
✅ Spracovaných 20300 URL...
✅ Spracovaných 20400 URL...
✅ Spracovaných 20500 URL...
✅ Spracovaných 20600 URL...
✅ Spracovaných 20700 URL...
✅ Spracovaných 20800 URL...
✅ Spracovaných 20900 URL...
✅ Spracovaných 21000 URL...
✅ Spracovaných 21100 URL...
✅ Spracovaných 21200 URL...
✅ Spracovaných 21300 URL...
✅ Spracovaných 21400 URL...
✅ Spracovaných 21500 URL...
✅ Spracovaných 21600 URL...
✅ Spracovaných 21700 URL...
✅ Spracovaných 21800 URL...
✅ Spracovaných 21900 URL...
✅ Spracovaných 22000 URL...
✅ Spracovaných 22100 URL...
✅ Spracovaných 22200 URL...
✅ Spracovaných 22300 URL...
✅ Spracovaných 22400 URL...
✅ Spracovaných 22500 URL...
✅ Spracovaných 22600 URL...
✅ Spracovaných 22700 URL...
✅ Spracovaných 22800 URL...
✅ Spracovaných 22900 URL...
✅ Spracovaných 23000 URL...
✅ Spracovaných 23100 URL...
✅ Spracovaných 23200 URL...
✅ Spracovaných 23300 URL...
✅ Spracovaných 23400 URL...
✅ Spracovaných 23500 URL...
✅ Spracovaných 23600 URL...
✅ Spracovaných 23700 URL...
✅ Spracovaných 23800 URL...
✅ Spracovaných 23900 URL...
✅ Spracovaných 24000 URL...
✅ Spracovaných 24100 URL...
✅ Spracovaných 24200 URL...
✅ Spracovaných 24300 URL...
✅ Spracovaných 24400 URL...
✅ Spracovaných 24500 URL...
✅ Spracovaných 24600 URL...
✅ Spracovaných 24700 URL...
✅ Spracovaných 24800 URL...
✅ Spracovaných 24900 URL...
✅ Spracovaných 25000 URL...
✅ Spracovaných 25100 URL...
✅ Spracovaných 25200 URL...
✅ Spracovaných 25300 URL...
✅ Spracovaných 25400 URL...
✅ Spracovaných 25500 URL...
✅ Spracovaných 25600 URL...
✅ Spracovaných 25700 URL...
✅ Spracovaných 25800 URL...
✅ Spracovaných 25900 URL...
✅ Spracovaných 26000 URL...
✅ Spracovaných 26100 URL...
✅ Spracovaných 26200 URL...
✅ Spracovaných 26300 URL...
✅ Spracovaných 26400 URL...
✅ Spracovaných 26500 URL...
✅ Spracovaných 26600 URL...
✅ Spracovaných 26700 URL...
✅ Spracovaných 26800 URL...
✅ Spracovaných 26900 URL...
✅ Spracovaných 27000 URL...
✅ Spracovaných 27100 URL...
✅ Spracovaných 27200 URL...
✅ Spracovaných 27300 URL...
✅ Spracovaných 27400 URL...
✅ Spracovaných 27500 URL...
✅ Spracovaných 27600 URL...
✅ Spracovaných 27700 URL...
✅ Spracovaných 27800 URL...
✅ Spracovaných 27900 URL...
✅ Spracovaných 28000 URL...

✅ Uložené do súboru: ../dataset/url_new_features_benign1.csv
Počet spracovaných URL: 28000

,num_subdomains,path_depth,has_www,has_double_https,has_port,has_fragment,url_ratio_digits,url_ratio_specials,contains_encoded_chars,has_repeat_chars,domain_entropy,domain_char_diversity,domain_has_digit,domain_starts_with_digit,tld_length,entropy_per_len,url
0,1,2,1,0,0,0,0.000000,0.181818,0,0,1.918296,0.666667,0,0,3,0.274042,https://www.google.com/corporate/
1,1,1,1,0,0,0,0.023256,0.162791,0,0,2.521641,0.857143,0,0,3,0.315205,https://www.youtube.com/watch?v=Vk0IGCCwvus
2,1,1,1,0,0,0,0.000000,0.161290,0,0,2.750000,0.875000,0,0,3,0.305556,https://www.facebook.com/Cogeco
3,1,0,1,0,0,0,0.000000,0.190476,0,0,2.321928,1.000000,0,0,3,0.386988,https://www.baidu.com
4,2,2,1,0,0,0,0.000000,0.153846,0,0,2.641604,0.777778,0,0,3,0.264160,https://www.en.wikipedia.org/wiki/Robertson_Ma...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,2,4,0,0,0,0,0.000000,0.196078,0,0,1.584963,1.000000,0,0,3,0.396241,https://ftp.aset.psu.edu/pub/ger/fortran/tulsi...
27996,1,2,0,0,0,0,0.000000,0.159091,0,0,2.641604,0.777778,0,0,3,0.264160,https://en.wikipedia.org/wiki/Terry_Winograd
27997,0,2,0,0,0,0,0.021739,0.152174,0,0,3.101881,0.529412,0,0,2,0.172327,https://pagesperso-orange.fr/adalog/compo2.htm
27998,1,2,0,0,0,0,0.000000,0.200000,0,0,2.500000,0.750000,0,0,2,0.277778,https://hem.passagen.se/zeela/
27999,1,6,0,0,0,0,0.156863,0.215686,0,0,0.918296,0.666667,0,0,3,0.229574,https://money.cnn.com/2001/03/06/sbrunning/biz...